name: Sync Files
on:
  push:
    branches:
      - master
      - UAT
      - QA
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          branch: ${{ github.ref_name }}
          PR_LABELS: |
            automerge