name: Sync Files
on:
  # push:
  #   branches:
  #     - master
  #     - UAT
  #     - QA
  
  pull_request:
    types: [ labeled, opened, unlabeled, closed ]

  workflow_dispatch:
env:
  BRANCH: ${{ github.ref_name }}
  # LABEL: ${{ github.event.label.name }}

jobs:
  sync-master:
    # if: |
    #   github.event.label.name != 'sync' && 
    #   github.event.pull_request.base.ref == 'master'
    if: github.ref_name == 'master' && github.event.label.name != 'nosync'  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync-master.yml
          PR_LABELS: |
            automerge
  sync-UAT:
    if: github.ref_name == 'UAT' && github.event.label.name != 'nosync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync-UAT.yml
          PR_LABELS: |
            automerge
  sync-QA:
    if: github.ref_name == 'QA' && github.event.label.name != 'nosync'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}
          CONFIG_PATH: .github/sync-QA.yml
          PR_LABELS: |
            automerge