name: test-label

on: 
  pull_request:
    types:
      - "labeled"
      - "closed"


jobs:
  test-pr-label:
    runs-on: ubuntu-latest
    steps:
      - name: test-label
        shell: bash
        run: |
          SHA=${{ github.event.label.name }}
          echo "GITHUB_SHA = ${SHA}"
