name: test-label

on: 
  pull_request:
    types:
      - "labeled"
      - "closed"


jobs:
  test-pr-label:
    runs-on: ubuntu-latest
    steps:
      - name: test-label
        shell: bash
        run: |
          SHA=${{ github.event.label.name }}
          echo "GITHUB_SHA = ${SHA}"
  build:
    name: Input check
    runs-on: ubuntu-latest
    steps:
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
          echo "github.event.pull_request.description           : $MSG_RAW"

        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
          MSG_RAW: ${{ github.event.pull_request.description }}
